import type { ElementContext } from './types.js';

export function serializeToMarkdown(ctx: ElementContext, sessionId: string): string {
  const componentName = ctx.source?.componentName ?? ctx.tagName;
  const file = ctx.source?.file ?? 'unknown';
  const line = ctx.source?.line ?? 0;
  const classStr = ctx.classList.length > 0 ? `.${ctx.classList.join('.')}` : '';

  const sections: string[] = [];

  // Header
  sections.push(`## Component: ${componentName}`);
  sections.push(`**File:** ${file}:${line}`);
  sections.push(`**Element:** ${ctx.tagName}${classStr}`);
  sections.push(`**DOM path:** ${ctx.domPath}`);
  sections.push('');
  sections.push('---');
  sections.push('');

  // Before screenshot
  sections.push('### Before');
  sections.push(`> Screenshot saved to: .daub-output/${sessionId}/before.png`);
  sections.push('');

  // After screenshot (conditional)
  if (ctx.screenshotAfter) {
    sections.push('### After (your sketch)');
    sections.push(`> Screenshot saved to: .daub-output/${sessionId}/after.png`);
    sections.push('');
  }

  // Annotations (conditional)
  if (ctx.screenshotAnnotated) {
    sections.push('### Annotations');
    sections.push(`> Screenshot saved to: .daub-output/${sessionId}/annotated.png`);
    sections.push('');
  }

  sections.push('---');
  sections.push('');

  // CSS delta (conditional)
  if (ctx.cssDelta.length > 0) {
    sections.push('### CSS delta');
    sections.push('| Property | Before | After |');
    sections.push('|---|---|---|');
    for (const d of ctx.cssDelta) {
      sections.push(`| ${d.property} | ${d.before} | ${d.after} |`);
    }
    sections.push('');
  }

  // Tailwind classes (conditional)
  if (ctx.tailwindClasses.length > 0) {
    sections.push('### Tailwind classes on element');
    sections.push(`\`${ctx.tailwindClasses.join(' ')}\``);
    sections.push('');
  }

  // DOM subtree
  sections.push('### DOM subtree (depth 3)');
  sections.push('```html');
  sections.push(ctx.htmlSubtree.length > 5000 ? ctx.htmlSubtree.slice(0, 5000) + '\n<!-- truncated -->' : ctx.htmlSubtree);
  sections.push('```');
  sections.push('');

  // Notes
  sections.push('### Notes');
  sections.push(ctx.notes || '(none)');
  sections.push('');

  // Footer
  sections.push('---');
  sections.push(`*Generated by Daub — .daub-output/${sessionId}/*`);

  return sections.join('\n');
}
