import { describe, it, expect } from 'vitest';
import { serializeToMarkdown } from '../serializer.js';
import type { ElementContext } from '../types.js';

function makeContext(overrides: Partial<ElementContext> = {}): ElementContext {
  return {
    source: { file: 'src/components/Card.tsx', line: 12, column: 0, componentName: 'Card', framework: 'react' },
    tagName: 'div',
    domPath: 'div#root > div.app > div.card',
    classList: ['card', 'p-4', 'bg-white'],
    htmlSubtree: '<div class="card"><p>Hello</p></div>',
    computedStyles: {} as any,
    tailwindClasses: ['p-4', 'bg-white'],
    rect: { top: 100, left: 200, width: 300, height: 150 },
    screenshotBefore: 'data:image/png;base64,abc',
    screenshotAfter: null,
    screenshotAnnotated: null,
    cssDelta: [],
    capturedAt: Date.now(),
    notes: '',
    ...overrides,
  };
}

describe('serializeToMarkdown', () => {
  it('includes all sections when every field is populated', () => {
    const ctx = makeContext({
      cssDelta: [{ property: 'gap', before: '8px', after: '16px' }],
      screenshotAfter: 'data:image/png;base64,after',
      screenshotAnnotated: 'data:image/png;base64,annotated',
      tailwindClasses: ['p-4', 'bg-white'],
      notes: 'Fix the gap',
    });
    const output = serializeToMarkdown(ctx, 'session1');

    expect(output).toContain('## Component: Card');
    expect(output).toContain('**File:** src/components/Card.tsx:12');
    expect(output).toContain('**Element:** div.card.p-4.bg-white');
    expect(output).toContain('**DOM path:** div#root > div.app > div.card');
    expect(output).toContain('### Before');
    expect(output).toContain('### After (your sketch)');
    expect(output).toContain('### Annotations');
    expect(output).toContain('### CSS delta');
    expect(output).toContain('### Tailwind classes on element');
    expect(output).toContain('`p-4 bg-white`');
    expect(output).toContain('### DOM subtree (depth 3)');
    expect(output).toContain('### Notes');
    expect(output).toContain('Fix the gap');
    expect(output).toContain('*Generated by Daub');
  });

  it('renders component header with componentName', () => {
    const output = serializeToMarkdown(makeContext(), 'sess');
    expect(output).toContain('## Component: Card');
  });

  it('renders file and line from source', () => {
    const output = serializeToMarkdown(makeContext(), 'sess');
    expect(output).toContain('**File:** src/components/Card.tsx:12');
  });

  it('renders element with classes joined by dots', () => {
    const output = serializeToMarkdown(makeContext(), 'sess');
    expect(output).toContain('**Element:** div.card.p-4.bg-white');
  });

  it('renders DOM path', () => {
    const output = serializeToMarkdown(makeContext(), 'sess');
    expect(output).toContain('**DOM path:** div#root > div.app > div.card');
  });

  it('falls back to tagName when source is null', () => {
    const ctx = makeContext({ source: null });
    const output = serializeToMarkdown(ctx, 'sess');
    expect(output).toContain('## Component: div');
    expect(output).toContain('**File:** unknown:0');
  });

  it('renders just tagName with no dots when classList is empty', () => {
    const ctx = makeContext({ classList: [] });
    const output = serializeToMarkdown(ctx, 'sess');
    expect(output).toContain('**Element:** div');
    expect(output).not.toContain('**Element:** div.');
  });

  it('always includes the Before screenshot section', () => {
    const output = serializeToMarkdown(makeContext(), 'sess');
    expect(output).toContain('### Before');
    expect(output).toContain('.daub-output/sess/before.png');
  });

  it('omits After section when screenshotAfter is null', () => {
    const ctx = makeContext({ screenshotAfter: null });
    const output = serializeToMarkdown(ctx, 'sess');
    expect(output).not.toContain('### After');
    expect(output).not.toContain('after.png');
  });

  it('includes After section when screenshotAfter is present', () => {
    const ctx = makeContext({ screenshotAfter: 'data:image/png;base64,xyz' });
    const output = serializeToMarkdown(ctx, 'sess');
    expect(output).toContain('### After (your sketch)');
    expect(output).toContain('.daub-output/sess/after.png');
  });

  it('omits Annotations section when screenshotAnnotated is null', () => {
    const ctx = makeContext({ screenshotAnnotated: null });
    const output = serializeToMarkdown(ctx, 'sess');
    expect(output).not.toContain('### Annotations');
    expect(output).not.toContain('annotated.png');
  });

  it('includes Annotations section when screenshotAnnotated is present', () => {
    const ctx = makeContext({ screenshotAnnotated: 'data:image/png;base64,xyz' });
    const output = serializeToMarkdown(ctx, 'sess');
    expect(output).toContain('### Annotations');
    expect(output).toContain('.daub-output/sess/annotated.png');
  });

  it('omits CSS delta section when cssDelta is empty', () => {
    const ctx = makeContext({ cssDelta: [] });
    const output = serializeToMarkdown(ctx, 'sess');
    expect(output).not.toContain('### CSS delta');
    expect(output).not.toContain('| Property |');
  });

  it('renders CSS delta as a markdown table when cssDelta has entries', () => {
    const ctx = makeContext({
      cssDelta: [{ property: 'gap', before: '8px', after: '16px' }],
    });
    const output = serializeToMarkdown(ctx, 'sess');
    expect(output).toContain('### CSS delta');
    expect(output).toContain('| Property | Before | After |');
    expect(output).toContain('|---|---|---|');
    expect(output).toContain('| gap | 8px | 16px |');
  });

  it('omits Tailwind section when tailwindClasses is empty', () => {
    const ctx = makeContext({ tailwindClasses: [] });
    const output = serializeToMarkdown(ctx, 'sess');
    expect(output).not.toContain('### Tailwind classes on element');
  });

  it('renders Tailwind classes as inline code when present', () => {
    const ctx = makeContext({ tailwindClasses: ['p-4', 'bg-white'] });
    const output = serializeToMarkdown(ctx, 'sess');
    expect(output).toContain('### Tailwind classes on element');
    expect(output).toContain('`p-4 bg-white`');
  });

  it('truncates htmlSubtree longer than 5000 characters', () => {
    const longHtml = '<div>' + 'a'.repeat(6000) + '</div>';
    const ctx = makeContext({ htmlSubtree: longHtml });
    const output = serializeToMarkdown(ctx, 'sess');
    expect(output).toContain('<!-- truncated -->');
    expect(output).not.toContain(longHtml);
  });

  it('renders (none) when notes is empty', () => {
    const ctx = makeContext({ notes: '' });
    const output = serializeToMarkdown(ctx, 'sess');
    expect(output).toContain('### Notes');
    expect(output).toContain('(none)');
  });

  it('renders notes content when notes is non-empty', () => {
    const ctx = makeContext({ notes: 'Fix the gap' });
    const output = serializeToMarkdown(ctx, 'sess');
    expect(output).toContain('### Notes');
    expect(output).toContain('Fix the gap');
  });

  it('includes session ID in screenshot paths', () => {
    const output = serializeToMarkdown(makeContext(), 'abc123');
    expect(output).toContain('.daub-output/abc123/');
  });

  it('ends with the Generated by Daub footer', () => {
    const output = serializeToMarkdown(makeContext(), 'abc123');
    expect(output).toContain('*Generated by Daub — .daub-output/abc123/*');
  });
});
